// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk0hC6KB4ePPclsuB9K9BpMR8pw2_aQbM',
    appId: '1:145574268937:web:c6e7acb9edc8da4e33e8d8',
    messagingSenderId: '145574268937',
    projectId: 'authenticationapp-a94f8',
    authDomain: 'authenticationapp-a94f8.firebaseapp.com',
    databaseURL: 'https://authenticationapp-a94f8-default-rtdb.firebaseio.com',
    storageBucket: 'authenticationapp-a94f8.firebasestorage.app',
    measurementId: 'G-KDZEBKW3VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx1dQhE-XTuXGfDgvXyV6ZTwISTn6gaG8',
    appId: '1:145574268937:android:cee5e03ae558290c33e8d8',
    messagingSenderId: '145574268937',
    projectId: 'authenticationapp-a94f8',
    databaseURL: 'https://authenticationapp-a94f8-default-rtdb.firebaseio.com',
    storageBucket: 'authenticationapp-a94f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRMa92mjE4rcUVZVUW8sgA6EKDU0RMPMA',
    appId: '1:145574268937:ios:ef6713e375d5e96d33e8d8',
    messagingSenderId: '145574268937',
    projectId: 'authenticationapp-a94f8',
    databaseURL: 'https://authenticationapp-a94f8-default-rtdb.firebaseio.com',
    storageBucket: 'authenticationapp-a94f8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRMa92mjE4rcUVZVUW8sgA6EKDU0RMPMA',
    appId: '1:145574268937:ios:ef6713e375d5e96d33e8d8',
    messagingSenderId: '145574268937',
    projectId: 'authenticationapp-a94f8',
    databaseURL: 'https://authenticationapp-a94f8-default-rtdb.firebaseio.com',
    storageBucket: 'authenticationapp-a94f8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk0hC6KB4ePPclsuB9K9BpMR8pw2_aQbM',
    appId: '1:145574268937:web:28a9e0ea6b00512933e8d8',
    messagingSenderId: '145574268937',
    projectId: 'authenticationapp-a94f8',
    authDomain: 'authenticationapp-a94f8.firebaseapp.com',
    databaseURL: 'https://authenticationapp-a94f8-default-rtdb.firebaseio.com',
    storageBucket: 'authenticationapp-a94f8.firebasestorage.app',
    measurementId: 'G-W0BF8QB7RE',
  );
}
